version: '3'

volumes:
  postgres_volume_local:
  postgres_volume_prod:

services:
  pg-local:
    image: postgres:16-alpine3.20
    env_file:
      - "local.env"
    ports:
      - "50003:5432"
    volumes:
      - postgres_volume_local:/var/lib/postgreqsl/data_auth
  
  pg-prod:
    image: postgres:16-alpine3.20
    env_file:
      - "prod.env"
    ports:
      - "50004:5432"
    volumes:
      - postgres_volume_prod:/var/lib/postgreqsl/data_auth
  
  migrator-local:
    build:
      context: .
      dockerfile: migration_local.dockerfile
    restart: on-failure
    environment:
      DB_HOST: pg-local

  migrator-prod:
    build:
      context: .
      dockerfile: migration_prod.dockerfile
    restart: on-failure
    environment:
      DB_HOST: pg-prod
  