version: "3"

volumes:
  postgres_volume_local:
  postgres_volume_prod:

services:
  jaeger:
    image: jaegertracing/all-in-one:1.48
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp" # jaeger-client
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686" # web
      - "14268:14268"
      - "9411:9411"

  pg-local:
    image: postgres:16-alpine3.20
    env_file:
      - "env/local.env"
    ports:
      - "50003:5432"
    volumes:
      - postgres_volume_local:/var/lib/postgresql/data

  migrator-local:
    build:
      context: .
      dockerfile: migrations/local/migration_local.dockerfile
    restart: on-failure
    environment:
      DB_HOST: pg-local

  # pg-prod:
  #   image: postgres:16-alpine3.20
  #   env_file:
  #     - "env/prod.env"
  #   ports:
  #     - "50004:5432"
  #   volumes:
  #     - postgres_volume_prod:/var/lib/postgresql/data

  # migrator-prod:
  #   build:
  #     context: .
  #     dockerfile: migrations/prod/migration_prod.dockerfile
  #   restart: on-failure
  #   environment:
  #     DB_HOST: pg-prod
